import streamlit as st
st.set_page_config(layout="wide")
st.title("展示")
st.subheader("1.项目内容", divider=True)
st.write("为了优化项目结构，本人拆分了new-homepage项目，本项目包含展示类内容，原项目保留在Streamlit Cloud但不再更新。")
st.write("LLM查询页面记录了我使用LLM查询的难以用传统搜索引擎查找的问题，可以分页查看、随机显示或搜索相应文件。")
st.write("AI图片页面为使用Hunyuan Video生成的的图片，可以选择特定提示词对应的文件夹或随机选择文件夹。")
st.write("AI视频页面包含使用Wan2.1 1.3b生成的视频，可以根据视频主题选择对应的文件夹或随机选择文件夹。")
st.write("LLM散文集页面是新创建的，展示了使用在写作上有优势的思维链模型写的文章以及对应的语音。")
st.subheader("2.开发原因", divider=True)
st.write("本人使用Streamlit创建项目的原因是语法较为简洁，并且能对接我较为熟悉的Python生态，语法简洁在LLM辅助开发上也有优势。")
st.write("本人创建个人网站的一方面原因是作为编程实践，另一方面使用个人网站相比社交平台在设计和内容上较为自由，也可以发挥Python生态优势实现更多功能。")
st.subheader("3.我的其它项目", divider=True)
st.write("我的GitHub名称是willian7004，命名时笔误了，在streamlit cloud的域名均使用william7004的名称。其它项目可以在我的GitHub仓库查看，博客部分也提到了其中一些项目和技术路线。")
